# waypoints formated as x, y, yaw(radians)
line_to_manipulator: 
  [-0.741, 3.468, 0.599] 
delivery_pose:
  [-3.022, -0.903, -0.041]
load_bricks:
  [0.522, -0.063, -0.443]
charge:
  [0.430, 0.047, 1.839] # 3
  # [0.809, 0.483, 1.469] # dock 1
stopping_tag: "wc_3_entrance"
