
base_link_id: /map #base_link
action_topic: mission/action_state
# waypoints formated as x, y, yaw(radians)
line_to_manipulator: 
  [1.338, 1.297, 2.3562] # 3pi/4
line_from_manipulator:
  [0.816, 1.171, 5.4978]
load_bricks:
  [5, 2.3, 0.0]
charge_initial:
  [1, 1, 1.57]
charge_dock:
  [3, 1, 0.0]
#Relative movements
90degrees_left:
  [0, 0, 1.57]
90degrees_right:
  [0, 0, -1.57]
180degrees_turn:
  [0, 0, 3.14]