[
  "line_in",
  "line_out",
  "wc_1_entrance",
  "wc_1_exit",
  "wc_1_conveyer",
  "wc_1_load",
  "wc_2_entrance",
  "wc_2_exit",
  "wc_2_conveyer",
  "wc_2_load",
  "wc_3_entrance",
  "wc_3_exit",
  "wc_3_conveyer",
  "wc_3_load"
]
