#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d

#Set the update and publish frequency of the costmap
update_frequency: 5.0
publish_frequency: 2.0

# costmap grid specific parameters
map_type: costmap # voxel is 3D view
track_unknown_space: false
publish_cost_grid: true

#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 0.2

#Obstacle marking parameters
obstacle_range: 3.0 # only update add obstacle within this range
max_obstacle_height: 0.4
raytrace_range: 3.0 # only clear space out to this range
sim_time: 1

#The footprint of the robot and associated padding
footprint:  [
[-0.220000, -0.080000],
[-0.120000, -0.160000],
[-0.109000, -0.160000],
[-0.109000, -0.195000],
[0.109000, -0.195000],
[0.109000, -0.160000],
[0.330000, -0.160000],
[0.330000, 0.160000],
[0.109000, 0.160000],
[0.109000, 0.195000],
[-0.109000, 0.195000],
[-0.109000, 0.160000],
[-0.220000, 0.100000]
]
footprint_padding: 0.02

#Cost function parameters
inflation_radius: 0.43
cost_scaling_factor: 10.0

#The cost at which a cell is considered an obstacle when a map is read from the map_server
lethal_cost_threshold: 100
