#Independent settings for the global planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

global_costmap:
  #Set the global and robot frames for the costmap
    
  global_frame: /map
  robot_base_frame: base_link

  #We'll use a map served by the map_server to initialize this costmap
  static_map: true
  rolling_window: false

  observation_sources: base_scan
  base_scan: {
      data_type: LaserScan,
      sensor_frame: base_laser_link,
      topic: /base_scan,
      expected_update_rate: .8,
      observation_persistence: 0.0,
      marking: false,
      clearing: false,
      max_obstacle_height: 0.4,
      min_obstacle_height: 0.08
  }
