#Independent settings for the global planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

global_costmap:
  #Set the global and robot frames for the costmap    
  robot_base_frame: base_link

  #We'll use a map served by the map_server to initialize this costmap
  static_map: true
  rolling_window: false


