#Independent settings for the local planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

local_costmap:

  #Set the global and robot frames for the costmap
  global_frame: odom
  robot_base_frame: base_link

  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  origin_x: 0.0
  origin_y: 0.0
  resolution: 0.025

  observation_sources: base_scan
  base_scan: {
      data_type: LaserScan,
      sensor_frame: laser_link,
      topic: /fmSensors/scan,
      expected_update_rate: .8,
      observation_persistence: 0.0,
      marking: true,
      clearing: true,
      max_obstacle_height: 0.4,
      min_obstacle_height: -0.05
  }
